name: fantasy
description: Fantasy - animate your drawings

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  built_collection: ^5.1.1
  built_value: ^8.1.3
  rxdart: ^0.27.3
  path_provider: ^2.0.8
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.4+4
  #image_cropper: ^1.4.1
  permission_handler: ^8.3.0

  #admob
  #firebase_core: ^1.10.6
  #firebase_analytics: ^9.0.4
  google_mobile_ads: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  built_value_generator: ^8.1.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
